
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm install --save simple-statistics
      npm i svelte-chartjs
      npm add graphql-request graphql
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser



vscode:
  extensions:
    - svelte.svelte-vscode

    - mhutchie.git-graph

    - GraphQL.vscode-graphql

    - fivethree.vscode-svelte-snippets

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
