
tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 3000`
      npm install --save simple-statistics
      npm i svelte-chartjs
      npm install realm-web
      npm add graphql-request graphql
      npm install -D tailwindcss postcss autoprefixer svelte-preprocess
      npm i daisyui
      npm run dev

ports:
  - port: 3000
    onOpen: open-browser



vscode:
  extensions:
    - svelte.svelte-vscode

    - mhutchie.git-graph

    - GraphQL.vscode-graphql

    - fivethree.vscode-svelte-snippets

    - bradlc.vscode-tailwindcss

    - mongodb.mongodb-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
